### PR TITLE
switch to guru. oracle has been deprecated.

### PR DESCRIPTION
**Pull request by ottob**
see https://github.com/Microsoft/vscode-go/issues/284

### CODE REVIEW

**Comment by liuhewei** [comment]
Thanks for the notice. I really see that the oracle's code has not been changed over 2 months.
Because this plugin also integrates oracle tool for more features such as callee, callers, referers... Maybe should use guru to replace oracle totally. @ottob Have you done this?

**Comment by ottob** [comment]
Switching all features to guru seems correct. I don't use the other features but I can try, it might take some time though.

May I ask why you dropped support for godef? It seems much faster than oracle/guru to me.

**Comment by liuhewei** [comment]
Acutally, I don't find the difference between godef and oracle/guru in my environment. You feel that godef is "faster"? If you want, you can add it back as an configuration item, just like what has been done in GoTools :-)

I personally use the oracle callers frequently, also I added this command into the context menu. I'm a little busy this weekend, and I think you understand "guru" better than me, so if you don't mind and happen to be free, I hope you could implement it. You might only need modify the "gotools_oracle.py" to "gotools_guru.py" and do some verification on your environment, also a little change on "Default.sublime-commands" and "Context.sublime-menu" if you want.

Thanks :-)

**Comment by ottob** [comment]
In my medium size project:
GoTools: DEBUG: godef time: 0.03058910369873047 seconds
GoTools: DEBUG: guru time: 2.1328439712524414 seconds

Thats quite a bit of difference. Will put up a PR soon.

**Comment by ottob** [comment]
Updated commit. Only very lightly tested but seems to work.

**Comment by liuhewei** [comment]
Thanks, I'll have a try :-)

**Pull request merged**
